Guns = {
    "bandage",
    "medkit",
    "morphine",
    "painkiller",

    "weapon_jmoddynamite",
    "weapon_jmodflash",
    "weapon_jmodnade",

    "weapon_akm",
    "weapon_aks74u",
    "weapon_ar15",
    "weapon_asval",
    "weapon_beretta",
    "weapon_civil_famas",
    "weapon_cz75-2",
    "weapon_deagle",
    "weapon_l85a1",
    "weapon_galil",
    "weapon_glock",
    "weapon_gurkha",
    "weapon_hg_bat",
    "weapon_hk_usp",
    "weapon_hk_usps",
    "weapon_hk416-2",
    "weapon_kabar",
    "weapon_knife",
    "weapon_l1a1",
    "weapon_m134",
    "weapon_m14",
    "weapon_m1a1",
    "weapon_m249",
    "weapon_m4a1",
    "weapon_m4super-2",
    "weapon_minu14",
    "weapon_mp5a3",
    "weapon_mp7",
    "weapon_p228",
    "weapon_p90-2",
    "weapon_p99",
    "weapon_physgun",
    "weapon_pipe",
    "weapon_remington870",
    "weapon_rpk",
    "weapon_sar2",
    "weapon_spas12",
    "weapon_taser",
    "weapon_tomahawk-2",
    "weapon_ump",
    "weapon_xm1014",

}

GunsModel = {
    ["food_fishcan"] = "models/jordfood/atun.mdl",
    ["food_lays"] = "models/foodnhouseholditems/chipslays5.mdl",
    ["food_monster"] = "models/jorddrink/mongcan1a.mdl",
    ["food_spongebob_home"] = "models/jordfood/can.mdl",

    ["bandage"] = "models/weapons/medical/bandages/bandages.mdl",
    ["medkit"] = "models/weapons/medical/medkit/w_medkit.mdl",
    ["morphine"] = "models/weapons/medical/morphine/w_eq_morphine.mdl",
    ["painkiller"] = "models/weapons/medical/painpills/w_painpills.mdl",

    ["weapon_jmoddynamite"] = "models/props_junk/flare.mdl",
    ["weapon_jmodflash"] = "models/jmod/explosives/grenades/flashbang/flashbang.mdl",
    ["weapon_jmodnade"] = "models/jmod/explosives/grenades/fragnade/w_fragjade.mdl",

    ["weapon_akm"] = "models/weapons/salat/w_akm/w_akm.mdl",
    ["weapon_aks74u"] = "models/weapons/salat/w_aks74u/w_aks74u.mdl",
    ["weapon_ar15"] = "models/weapons/salat/w_m4a1/w_m4a1.mdl",
    ["weapon_asval"] = "models/weapons/salat/w_asval/w_asval.mdl",
    ["weapon_beretta"] = "models/weapons/salat/w_m9/w_m9.mdl",
    ["weapon_civil_famas"] = "models/weapons/salat/w_famasg2/w_famasg2.mdl",
    ["weapon_cz75-2"] = "models/weapons/salat/w_cz75/w_cz75.mdl",
    ["weapon_deagle"] = "models/weapons/salat/w_deagle/w_matebahomeprotection.mdl",
    ["weapon_l85a1"] = "models/weapons/salat/w_l85a1/w_l85a1.mdl",
    ["weapon_galil"] = "models/weapons/salat/w_ace23/w_ace23.mdl",
    ["weapon_glock"] = "models/weapons/salat/w_glock17/w_glock17.mdl",
    ["weapon_gurkha"] = "models/weapons/w_knife_t.mdl",
    ["weapon_handcuffs"] = "models/weapons/flexcuffs/flexcuffs.mdl",
    ["weapon_hg_bat"] = "models/weapons/salat/w_hg_bat/w_knije_t.mdl",
    ["weapon_hk_usp"] = "models/weapons/salat/w_hk_usp/w_usptactical.mdl",
    ["weapon_hk_usps"] = "models/weapons/w_pist_usp_silencer.mdl",
    ["weapon_hk416-2"] = "models/weapons/salat/w_hk416/w_hk416.mdl",
    ["weapon_kabar"] = "models/weapons/salat/w_kabar/w_sog_knife.mdl",
    ["weapon_knife"] = "models/weapons/salat/w_knife/w_knife.mdl",
    ["weapon_l1a1"] = "models/weapons/insurgency/w_l1a1.mdl",
    ["weapon_m134"] = "models/weapons/salat/w_m134/w_m134.mdl",
    --["weapon_m14"] = "models/weapons/insurgency/w_m14.mdl",
    --["weapon_m1a1"] = "models/weapons/insurgency/w_m1a1.mdl",
    ["weapon_m249"] = "models/weapons/salat/w_m249/w_m249.mdl",
    ["weapon_m4a1"] = "models/weapons/salat/w_m4a1/w_m4a1.mdl",
    ["weapon_m4super-2"] = "models/weapons/salat/w_m4super90/w_m4super90.mdl",
    --["weapon_minu14"] = "models/weapons/insurgency/w_mini14.mdl",
    ["weapon_mp5a3"] = "models/weapons/salat/w_mp5a3/w_mp5a3.mdl",
    ["weapon_mp7"] = "models/weapons/salat/w_mp7/w_mp7.mdl",
    ["weapon_p228"] = "models/weapons/w_pist_p228.mdl",
    ["weapon_p90-2"] = "models/weapons/salat/w_p90/w_p90.mdl",
    ["weapon_p99"] = "models/weapons/salat/w_p99/w_p99.mdl",
    ["weapon_physgun"] = "models/weapons/w_physics.mdl",
    ["weapon_pipe"] = "models/props_canal/mattpipe.mdl",
    ["weapon_remington870"] = "models/weapons/salat/w_remington_870/w_remington_870.mdl",
    ["weapon_rpk"] = "models/weapons/salat/w_rpk/w_rpk.mdl",
    ["weapon_sar2"] = "models/weapons/salat/w_sar2/w_irifle.mdl",
    ["weapon_spas12"] = "models/weapons/salat/w_spas_12/w_spas_12.mdl",
    ["weapon_taser"] = "models/weapons/taser/w_taser.mdl",
    ["weapon_tomahawk-2"] = "models/weapons/salat/w_tomahawk/w_tomahawk.mdl",
    ["weapon_ump"] = "models/weapons/w_smg_ump45.mdl",
    ["weapon_xm1014"] = "models/weapons/salat/w_xm1014/w_xm1014.mdl",
}

ShootWait = {
    ["bandage"] = 0,

    ["weapon_akm"] = 0.1,
    ["weapon_aks74u"] = 0.075,
    ["weapon_ar15"] = 0.08,
    ["weapon_asval"] = 0.065,
    ["weapon_beretta"] = 0.08,
    ["weapon_civil_famas"] = 0.01,
    ["weapon_cz75-2"] = 0.08,
    ["weapon_deagle"] = 0.15,
    ["weapon_l85a1"] = 0.1,
    ["weapon_galil"] = 0.09,
    ["weapon_glock"] = 0.08,
    ["weapon_hk_usp"] = 0.08,
    ["weapon_hk_usps"] = 0.08,
    ["weapon_hk416-2"] = 0.07,
    ["weapon_l1a1"] = 0.1,
    ["weapon_m134"] = 0.02,
    ["weapon_m14"] = 0.15,
    ["weapon_m1a1"] = 0.15,
    ["weapon_m249"] = 0.075,
    ["weapon_m4a1"] = 0.07,
    ["weapon_m4super-2"] = 0.4,
    ["weapon_minu14"] = 0.15,
    ["weapon_mp5a3"] = 0.06,
    ["weapon_mp7"] = 0.06,
    ["weapon_p228"] = 0.08,
    ["weapon_p90-2"] = 0.05,
    ["weapon_p99"] = 0.08,
    ["weapon_remington870"] = 0.5,
    ["weapon_rpk"] = 0.1,
    ["weapon_sar2"] = 0.1,
    ["weapon_spas12"] = 0.15,
    ["weapon_ump"] = 0.11,
    ["weapon_xm1014"] = 0.2,
}

ReloadTime = {
    ["bandage"] = 0,

    ["weapon_akm"] = 2,
    ["weapon_aks74u"] = 2,
    ["weapon_ar15"] = 2,
    ["weapon_asval"] = 2,
    ["weapon_beretta"] = 2,
    ["weapon_civil_famas"] = 2,
    ["weapon_cz75-2"] = 2,
    ["weapon_deagle"] = 2,
    ["weapon_l85a1"] = 2,
    ["weapon_galil"] = 2,
    ["weapon_glock"] = 2,
    ["weapon_hk_usp"] = 2,
    ["weapon_hk_usps"] = 2,
    ["weapon_hk416-2"] = 2,
    ["weapon_l1a1"] = 2,
    ["weapon_m134"] = 2,
    ["weapon_m14"] = 2,
    ["weapon_m1a1"] = 2,
    ["weapon_m249"] = 4,
    ["weapon_m4a1"] = 2,
    ["weapon_m4super-2"] = 2,
    ["weapon_minu14"] = 2,
    ["weapon_mp5a3"] = 2,
    ["weapon_mp7"] = 2,
    ["weapon_p228"] = 2,
    ["weapon_p90-2"] = 2,
    ["weapon_p99"] = 2,
    ["weapon_remington870"] = 2,
    ["weapon_rpk"] = 4,
    ["weapon_sar2"] = 2,
    ["weapon_spas12"] = 2,
    ["weapon_ump"] = 2,
    ["weapon_xm1014"] = 2,
}


TwoHandedOrNo = {
    ["bandage"] = false,

    ["weapon_akm"] = true,
    ["weapon_aks74u"] = true,
    ["weapon_ar15"] = true,
    ["weapon_asval"] = true,
    ["weapon_beretta"] = false,
    ["weapon_civil_famas"] = true,
    ["weapon_cz75-2"] = false,
    ["weapon_deagle"] = false,
    ["weapon_l85a1"] = true,
    ["weapon_galil"] = true,
    ["weapon_glock"] = false,
    ["weapon_hk_usp"] = false,
    ["weapon_hk_usps"] = false,
    ["weapon_hk416-2"] = true,
    ["weapon_l1a1"] = true,
    ["weapon_m134"] = true,
    ["weapon_m14"] = true,
    ["weapon_m1a1"] = true,
    ["weapon_m249"] = true,
    ["weapon_m4a1"] = true,
    ["weapon_m4super-2"] = true,
    ["weapon_minu14"] = true,
    ["weapon_mp5a3"] = true,
    ["weapon_mp7"] = true,
    ["weapon_p228"] = false,
    ["weapon_p90-2"] = true,
    ["weapon_p99"] = false,
    ["weapon_remington870"] = true,
    ["weapon_rpk"] = true,
    ["weapon_sar2"] = true,
    ["weapon_spas12"] = true,
    ["weapon_ump"] = true,
    ["weapon_xm1014"] = true,
}

Automatic = {
    ["bandage"] = false,

    ["weapon_akm"] = true,
    ["weapon_aks74u"] = true,
    ["weapon_ar15"] = false,
    ["weapon_asval"] = true,
    ["weapon_beretta"] = false,
    ["weapon_civil_famas"] = false,
    ["weapon_cz75-2"] = true,
    ["weapon_deagle"] = false,
    ["weapon_l85a1"] = true,
    ["weapon_galil"] = true,
    ["weapon_glock"] = false,
    ["weapon_hk_usp"] = false,
    ["weapon_hk_usps"] = false,
    ["weapon_hk416-2"] = true,
    ["weapon_l1a1"] = false,
    ["weapon_m134"] = true,
    ["weapon_m14"] = false,
    ["weapon_m1a1"] = false,
    ["weapon_m249"] = true,
    ["weapon_m4a1"] = true,
    ["weapon_m4super-2"] = true,
    ["weapon_minu14"] = true,
    ["weapon_mp5a3"] = true,
    ["weapon_mp7"] = true,
    ["weapon_p228"] = false,
    ["weapon_p90-2"] = true,
    ["weapon_p99"] = false,
    ["weapon_remington870"] = false,
    ["weapon_rpk"] = true,
    ["weapon_sar2"] = true,
    ["weapon_spas12"] = true,
    ["weapon_ump"] = true,
    ["weapon_xm1014"] = false,

}