Guns = {
    "bandage",
    "medkit",
    "morphine",
    "painkiller",

    "weapon_ak74",
    "weapon_ak74u",
    "weapon_akm",
    "weapon_ar15",
    "weapon_bat",
    "weapon_beretta",
    "weapon_civil_famas",
    "weapon_deagle",
    "weapon_fal",
    "weapon_fiveseven",
    "weapon_galil",
    "weapon_galilsar",
    "weapon_glock",
    "weapon_glock18",
    "weapon_gurkha",
    "weapon_hk_usp",
    "weapon_hk_usps",
    "weapon_jmoddynamite",
    "weapon_jmodflash",
    "weapon_jmodnade",
    "weapon_kabar",
    "weapon_knife",
    "weapon_l1a1",
    "weapon_m14",
    "weapon_m1a1",
    "weapon_m249",
    "weapon_m3super",
    "weapon_m4a1",
    "weapon_minu14",
    "weapon_mk18",
    "weapon_mp40",
    "weapon_mp5",
    "weapon_mp7",
    "weapon_p220",
    "weapon_physgun",
    "weapon_pipe",
    "weapon_remington870",
    "weapon_rpk",
    "weapon_sar2",
    "weapon_spas12",
    "weapon_t",
    "weapon_taser",
    "weapon_ump",
    "weapon_xm1014",
}

GunsModel = {
    ["food_fishcan"] = "models/jordfood/atun.mdl",
    ["food_lays"] = "models/foodnhouseholditems/chipslays5.mdl",
    ["food_monster"] = "models/jorddrink/mongcan1a.mdl",
    ["food_spongebob_home"] = "models/jordfood/can.mdl",

    ["bandage"] = "models/weapons/medical/bandages/bandages.mdl",
    ["medkit"] = "models/weapons/medical/medkit/w_medkit.mdl",
    ["morphine"] = "models/weapons/medical/morphine/w_eq_morphine.mdl",
    ["painkiller"] = "models/weapons/medical/painpills/w_painpills.mdl",

    ["weapon_ak74"] = "models/pwb/weapons/w_m134.mdl",
    ["weapon_ak74u"] = "models/pwb/weapons/w_aks74u.mdl",
    ["weapon_akm"] = "models/pwb/weapons/w_akm.mdl",
    ["weapon_ar15"] = "models/pwb2/weapons/w_m4a1.mdl",
    ["weapon_bat"] = "models/weapons/w_knije_t.mdl",
    ["weapon_beretta"] = "models/pwb/weapons/w_m9.mdl",
    ["weapon_civil_famas"] = "models/pwb2/weapons/w_famasg2.mdl",
    ["weapon_deagle"] = "models/pwb2/weapons/w_matebahomeprotection.mdl",
    ["weapon_fal"] = "models/pwb/weapons/w_l85a1.mdl",
    ["weapon_fiveseven"] = "models/pwb/weapons/w_p99.mdl",
    ["weapon_galil"] = "models/pwb2/weapons/w_ace23.mdl",
    ["weapon_galilsar"] = "models/pwb2/weapons/w_asval.mdl",
    ["weapon_glock"] = "models/pwb/weapons/w_glock17.mdl",
    ["weapon_glock18"] = "models/weapons/insurgency/w_makarov.mdl",
    ["weapon_gurkha"] = "models/weapons/insurgency/w_gurkha.mdl",
    ["weapon_handcuffs"] = "models/freeman/flexcuffs.mdl",
    ["weapon_hk_usp"] = "models/pwb2/weapons/w_usptactical.mdl",
    ["weapon_hk_usps"] = "models/weapons/w_pist_usp_silencer.mdl",
    ["weapon_jmoddynamite"] = "models/props_junk/flare.mdl",
    ["weapon_jmodflash"] = "models/jmod/explosives/grenades/flashbang/flashbang.mdl",
    ["weapon_jmodnade"] = "models/jmod/explosives/grenades/fragnade/w_fragjade.mdl",
    ["weapon_kabar"] = "models/weapons/insurgency/w_marinebayonet.mdl",
    ["weapon_knife"] = "models/pwb/weapons/w_knife.mdl",
    ["weapon_l1a1"] = "models/weapons/insurgency/w_l1a1.mdl",
    ["weapon_m14"] = "models/weapons/insurgency/w_m14.mdl",
    ["weapon_m1a1"] = "models/weapons/insurgency/w_m1a1.mdl",
    ["weapon_m249"] = "models/pwb2/weapons/w_m249paratrooper.mdl",
    ["weapon_m3super"] = "models/pwb2/weapons/w_m4super90.mdl",
    ["weapon_m4a1"] = "models/pwb2/weapons/w_m4a1.mdl",
    ["weapon_minu14"] = "models/weapons/insurgency/w_mini14.mdl",
    ["weapon_mk18"] = "models/pwb/weapons/w_hk416.mdl",
    ["weapon_mp40"] = "models/pwb/weapons/w_p90.mdl",
    ["weapon_mp5"] = "models/pwb2/weapons/w_mp5a3.mdl",
    ["weapon_mp7"] = "models/pwb2/weapons/w_mp7.mdl",
    ["weapon_p220"] = "models/pwb/weapons/w_cz75.mdl",
    ["weapon_physgun"] = "models/weapons/w_physics.mdl",
    ["weapon_pipe"] = "models/props_canal/mattpipe.mdl",
    ["weapon_remington870"] = "models/pwb/weapons/w_remington_870.mdl",
    ["weapon_rpk"] = "models/pwb2/weapons/w_rpk.mdl",
    ["weapon_sar2"] = "models/weapons/arccw/w_irifle.mdl",
    ["weapon_spas12"] = "models/pwb/weapons/w_spas_12.mdl",
    ["weapon_t"] = "models/pwb/weapons/w_tomahawk.mdl",
    ["weapon_taser"] = "models/realistic_police/taser/w_taser.mdl",
    ["weapon_ump"] = "models/weapons/insurgency/w_ump45.mdl",
    ["weapon_xm1014"] = "models/pwb/weapons/w_xm1014.mdl",
}

ShootWait = {
    ["bandage"] = 0,

    ["weapon_ak74"] = 0.02,
    ["weapon_ak74u"] = 0.075,
    ["weapon_akm"] = 0.1,
    ["weapon_ar15"] = 0.08,
    ["weapon_beretta"] = 0.08,
    ["weapon_civil_famas"] = 0.01,
    ["weapon_deagle"] = 0.15,
    ["weapon_fal"] = 0.1,
    ["weapon_fiveseven"] = 0.08,
    ["weapon_galil"] = 0.09,
    ["weapon_galilsar"] = 0.065,
    ["weapon_glock"] = 0.08,
    ["weapon_glock18"] = 0.08,
    ["weapon_hk_usp"] = 0.08,
    ["weapon_hk_usps"] = 0.08,
    ["weapon_l1a1"] = 0.1,
    ["weapon_m14"] = 0.15,
    ["weapon_m1a1"] = 0.15,
    ["weapon_m249"] = 0.075,
    ["weapon_m3super"] = 0.4,
    ["weapon_m4a1"] = 0.07,
    ["weapon_minu14"] = 0.15,
    ["weapon_mk18"] = 0.07,
    ["weapon_mp40"] = 0.05,
    ["weapon_mp5"] = 0.06,
    ["weapon_mp7"] = 0.06,
    ["weapon_p220"] = 0.08,
    ["weapon_remington870"] = 0.5,
    ["weapon_rpk"] = 0.1,
    ["weapon_sar2"] = 0.1,
    ["weapon_spas12"] = 0.15,
    ["weapon_ump"] = 0.11,
    ["weapon_xm1014"] = 0.2,
}

ReloadTime = {
    ["bandage"] = 0,

    ["weapon_ak74"] = 2,
    ["weapon_ak74u"] = 2,
    ["weapon_akm"] = 2,
    ["weapon_ar15"] = 2,
    ["weapon_beretta"] = 2,
    ["weapon_civil_famas"] = 2,
    ["weapon_deagle"] = 2,
    ["weapon_fal"] = 2,
    ["weapon_fiveseven"] = 2,
    ["weapon_galil"] = 2,
    ["weapon_galilsar"] = 2,
    ["weapon_glock"] = 2,
    ["weapon_glock18"] = 2,
    ["weapon_hk_usp"] = 2,
    ["weapon_hk_usps"] = 2,
    ["weapon_l1a1"] = 2,
    ["weapon_m14"] = 2,
    ["weapon_m1a1"] = 2,
    ["weapon_m249"] = 4,
    ["weapon_m3super"] = 2,
    ["weapon_m4a1"] = 2,
    ["weapon_minu14"] = 2,
    ["weapon_mk18"] = 2,
    ["weapon_mp40"] = 2,
    ["weapon_mp5"] = 2,
    ["weapon_mp7"] = 2,
    ["weapon_p220"] = 2,
    ["weapon_remington870"] = 2,
    ["weapon_rpk"] = 4,
    ["weapon_sar2"] = 2,
    ["weapon_spas12"] = 2,
    ["weapon_ump"] = 2,
    ["weapon_xm1014"] = 2,
}


TwoHandedOrNo = {
    ["bandage"] = false,

    ["weapon_ak74"] = true,
    ["weapon_ak74u"] = true,
    ["weapon_akm"] = true,
    ["weapon_ar15"] = true,
    ["weapon_beretta"] = false,
    ["weapon_civil_famas"] = true,
    ["weapon_deagle"] = false,
    ["weapon_fal"] = true,
    ["weapon_fiveseven"] = false,
    ["weapon_galil"] = true,
    ["weapon_galilsar"] = true,
    ["weapon_glock"] = false,
    ["weapon_glock18"] = false,
    ["weapon_hk_usp"] = false,
    ["weapon_hk_usps"] = false,
    ["weapon_l1a1"] = true,
    ["weapon_m14"] = true,
    ["weapon_m1a1"] = true,
    ["weapon_m249"] = true,
    ["weapon_m3super"] = true,
    ["weapon_m4a1"] = true,
    ["weapon_minu14"] = true,
    ["weapon_mk18"] = true,
    ["weapon_mp40"] = true,
    ["weapon_mp5"] = true,
    ["weapon_mp7"] = true,
    ["weapon_p220"] = false,
    ["weapon_remington870"] = true,
    ["weapon_rpk"] = true,
    ["weapon_sar2"] = true,
    ["weapon_spas12"] = true,
    ["weapon_ump"] = true,
    ["weapon_xm1014"] = true,
}

Automatic = {
    ["bandage"] = false,

    ["weapon_ak74"] = true,
    ["weapon_ak74u"] = true,
    ["weapon_akm"] = true,
    ["weapon_ar15"] = false,
    ["weapon_beretta"] = false,
    ["weapon_civil_famas"] = false,
    ["weapon_deagle"] = false,
    ["weapon_fal"] = true,
    ["weapon_fiveseven"] = false,
    ["weapon_galil"] = true,
    ["weapon_galilsar"] = true,
    ["weapon_glock"] = false,
    ["weapon_glock18"] = false,
    ["weapon_hk_usp"] = false,
    ["weapon_hk_usps"] = false,
    ["weapon_l1a1"] = false,
    ["weapon_m14"] = false,
    ["weapon_m1a1"] = false,
    ["weapon_m249"] = true,
    ["weapon_m3super"] = true,
    ["weapon_m4a1"] = true,
    ["weapon_minu14"] = true,
    ["weapon_mk18"] = true,
    ["weapon_mp40"] = true,
    ["weapon_mp5"] = true,
    ["weapon_mp7"] = true,
    ["weapon_p220"] = true,
    ["weapon_remington870"] = false,
    ["weapon_rpk"] = true,
    ["weapon_sar2"] = true,
    ["weapon_spas12"] = true,
    ["weapon_ump"] = true,
    ["weapon_xm1014"] = false,
}