player_manager.AddValidModel( "female01 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/female_01.mdl" )
player_manager.AddValidHands( "female01 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "female02 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/female_02.mdl" )
player_manager.AddValidHands( "female02 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "female04 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/female_04.mdl" )
player_manager.AddValidHands( "female04 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "female06 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/female_06.mdl" )
player_manager.AddValidHands( "female06 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male02 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_02.mdl" )
player_manager.AddValidHands( "male02 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male04 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_04.mdl" )
player_manager.AddValidHands( "male04 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male05 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_05.mdl" )
player_manager.AddValidHands( "male05 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male06 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_06.mdl" )
player_manager.AddValidHands( "male06 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male07 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_07.mdl" )
player_manager.AddValidHands( "male07 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male08 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_08.mdl" )
player_manager.AddValidHands( "male08 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )
player_manager.AddValidModel( "male09 [Siberian Republic - Rebel]",		"models/player/sibresp/rebel/male_09.mdl" )
player_manager.AddValidHands( "male09 [Siberian Republic - Rebel]",		"models/weapons/c_arms_refugee.mdl",		0, "0100000" )